name: Run Cypress Tests and Publish to Alva

on:
  push:
    branches:
      - implementation-branch

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Application
        run: |
          npm start &
          wait-on http://localhost:3000 # Replace with your app's URL
        env:
          CI: true

      - name: Run Cypress Tests
        run: npx cypress run --headless

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports/mocha

      - name: Check and Process Test Results
        run: |
          TEST_RESULTS_FILE="cypress/reports/mocha/mochawesome.json"
          if [ -f "$TEST_RESULTS_FILE" ]; then
            echo "File found: $TEST_RESULTS_FILE"
            escapedResults=$(jq -c '[.results[].suites[].tests[] | {test: .title, result: .state}]' "$TEST_RESULTS_FILE" | sed 's/"/\\"/g')
            echo "Processed Results: $escapedResults"
          else
            echo "File not found: $TEST_RESULTS_FILE"
            exit 1
          fi
        env:
          CI: true
          
      - name: Fetch GitHub Repo Data
        run: |
          retry=0
          max_retries=3
          url="https://api.github.com/repos/ApGroups/notes-app-react"

          while [ $retry -le $max_retries ]; do
            echo "Attempt: $((retry + 1))"
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$url")

            if [ -n "$response" ]; then
              echo "Repo data: $response"
              break
            fi

            echo "Retrying..."
            retry=$((retry + 1))
            sleep 2
          done

          if [ -z "$response" ]; then
            echo "Error: Failed to fetch data from $url after $max_retries attempts."
            exit 1
          fi


  publish-to-alva:
    uses: DevSkillsHQ/publish-test-results-workflow/.github/workflows/publish-test-results.yml@main
    needs: cypress-tests
    permissions:
      contents: write
    secrets:
      AUTO_SCORE_TOKEN: ${{ secrets.AUTO_SCORE_TOKEN }}
